### ISSUE TITLE
Dependencies are missing in jar

### ISSUE THREAD

**Issue by QkiZMR** [dacrome/gradle-shadow-plugin-example#1]
I'm looking for a working example of using the shadow plugin. I compiled your project as it stands in instruction but generated jar doesn't have dependencies in the jar. There's only one class in the jar, your class. No commons-io, com.github.docker-java, com.google.inject classes.

**Comment by dacrome** [comment]
I guess you found the other branches, because you created #2 - run the gradle commands with the specific branches and read what to aspect in the readme.
